### ISSUE TITLE
Adding new resource

### ISSUE THREAD

**Issue by mikeyt120** [chrisleaman/awesome-coastal#47]
Hi Chris,

I've got a repository "coastal-glare-estimation" which includes code to estimate when glare will affect coastal cameras given a location and field of view. Just wondering if you would be interested in including the repository to your awesome-coastal resources list? I'm not very good with GitHub sorry, so not sure how to do the pull request to upload the repository.

https://github.com/mikeyt120/coastal-glare-estimation

Kind regards,
Michael

**Comment by chrisleaman** [comment]
Hi Michael, thanks for reaching out and cool tool! I've added your repo in under the "Terrestial and UAV video analysis" heading in 37f258454e5c023f34e337d73b181172e9ebdcf8.
